In [2]:
import numpy as np
import pandas as pd

In [6]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array * 2)

[[ 2  4  6]
 [ 8 10 12]]


In [7]:
zeros = np.zeros((2, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
stacked = np.array([[1, 2, 3],
                    [4, 5, 6]])
columns = np.array([[0],[0]])
with_rows = np.vstack((stacked,[[0,0,0],[0,0,0]]) )

print(with_rows)

[[1 2 3]
 [4 5 6]
 [0 0 0]
 [0 0 0]]


In [7]:
a = pd.Series([1, 2, 3, 4, 5], index=False)
print(a)

TypeError: Index(...) must be called with a collection of some kind, False was passed